import os
from config_pipeline import input_dict, resultspath, acemd_path, acemd_license
from simulate_structures_functions import define_production, job_commands, timestep, trajperiod, temperature, prod_simtime, repnum
#####################
## Part 4: Production
#####################

# Production protocol

# For each structure 
for entry in input_dict:    
    name = entry['name']
    pdbcode = entry['pdbcode']
    apo = entry['apo']
    # must match with equildir in equilibration launcher code and contain input and output of equilibration.
    modelname = name+'_apo' if apo else name
    equildir = '%s/equil/%s/' % (resultspath, modelname)
    if not os.path.exists(equildir):
        print("structure %s has not been yet equillibrated. Skipping...")
        continue
    for rep in range(1,repnum+1):
        
        try: 
            # If simulation for this PDB has already been run
            proddir='%sproduction/%s/rep_%d/' % (resultspath, modelname, rep)
            if os.path.exists(proddir+'/output.xtc') or os.path.exists(proddir+'simrunning'):
                print("replicate %d of structure %s already has been simulated" %(rep, modelname))
                continue
            
            print('submitting replicate %d of %s' % (rep, modelname))
            # directory copy output of equilibration to production input (initial working directory for run_prod.sh).
            define_production(equildir, proddir, timestep, trajperiod, temperature, prod_simtime)

            sq = SlurmQueue()
            sq.envvars = acemd_license
            sq.jobname = modelname+'_pr'+str(rep)
            sq.datadir = None
            sq.partition = 'gpcr_gpu'
            sq.prerun = job_commands(proddir, './%s_pr_%d/'%(modelname,rep))
            sq.ngpu = 1
            sq.ncpu = 1

            #Substitute run.sh generated by HTMD by a different one, adapted to the specified path of ACEMD
            with open(proddir + 'run.sh', 'w') as f:
                f.write('#!/bin/bash\n%s >%slog.txt 2>&1' % (acemd_path,proddir))

            sq.submit(proddir)
            
        except Exception as e:
            print("model "+modelname+" could not be send to production because of ",e)
